"use client";
import { useEffect, useMemo, useState } from "react";

type Quote={code:string;market:number;name:string;price:number;changePct:number;change:number;volume:number;amount:number;turnover:number;pe:number;pb:number;high:number;low:number;open:number;prevClose:number;marketCap:number};
type Bar={date:string;open:number;close:number;high:number;low:number;volume:number;changePct:number};
const INDEX_CODES=["1.000001","0.399001","0.399006","1.000688","1.000300"];
const DEFAULT_WATCH=["600519","300750","000858","601318"];
const chapters=[
 ["基础","收益率与年化","总收益率 =（期末价值－本金＋现金分红）÷ 本金。例：10万元变为10.8万元，总收益率8%。年化收益率用于统一比较不同持有期。"],
 ["基础","复利与72法则","复利终值 = 本金×(1+收益率)^年数。年化8%时，72÷8≈9年翻倍；这是近似估算，不是承诺。"],
 ["基础","波动率与最大回撤","回撤衡量从历史高点下跌的幅度。净值从1.20跌到0.90，回撤=(0.90/1.20)-1=-25%。"],
 ["基础","市价、限价与成交","市价单优先成交但价格不确定；限价买单只会在限定价格或更低成交。流动性差时滑点会放大。"],
 ["进阶","PE、PB 与 PEG","PE=股价÷每股收益；PEG=PE÷预期增长率。PE 30倍、增速20%，PEG=1.5。增长预测失真时PEG也会失真。"],
 ["进阶","三张财务报表","利润不等于现金。净利润增长但经营现金流持续为负，需要检查应收账款、存货和收入确认。"],
 ["进阶","自由现金流与 DCF","自由现金流≈经营现金流－资本开支。DCF把未来现金流按要求回报率折现，结果对增速和折现率极敏感。"],
 ["进阶","均线、MACD 与 RSI","指标用于验证价格结构，不单独构成买卖理由。RSI高表示近期涨势强，不必然意味着立刻下跌。"],
 ["高阶","相关性与资产配置","相关性越低，组合分散效果通常越好。两项资产各50%，风险并非两者风险的简单平均。"],
 ["高阶","仓位与凯利公式","凯利比例 f=(bp-q)/b。胜率55%、盈亏比1:1时，f=10%；实务常用半凯利降低估计误差风险。"],
 ["高阶","利率与估值传导","无风险利率上升会提高折现率，压低远期现金流现值，因此久期更长的成长资产通常更敏感。"],
 ["高阶","行为金融与交易纪律","损失厌恶、锚定和确认偏误会破坏纪律。预先写下触发、失效条件，比盘中临时决定更可靠。"],
];
const money=(n:number)=>!Number.isFinite(n)?"-":n>=1e8?`${(n/1e8).toFixed(2)}亿`:n>=1e4?`${(n/1e4).toFixed(2)}万`:n.toLocaleString("zh-CN");
const pct=(n:number)=>Number.isFinite(n)?`${n>=0?"+":""}${n.toFixed(2)}%`:"-";

export default function Home(){
 const [tab,setTab]=useState("market"),[quotes,setQuotes]=useState<Quote[]>([]),[bars,setBars]=useState<Bar[]>([]),[selected,setSelected]=useState("600519"),[loading,setLoading]=useState(true),[error,setError]=useState(""),[stamp,setStamp]=useState(""),[watch,setWatch]=useState<string[]>(DEFAULT_WATCH),[newCode,setNewCode]=useState(""),[holdings,setHoldings]=useState<{code:string;shares:number;cost:number}[]>([]),[learnQ,setLearnQ]=useState(""),[lesson,setLesson]=useState(0),[principal,setPrincipal]=useState(100000),[rate,setRate]=useState(8),[years,setYears]=useState(10);
 useEffect(()=>{try{setWatch(JSON.parse(localStorage.getItem("wealth-watch")||"null")||DEFAULT_WATCH);setHoldings(JSON.parse(localStorage.getItem("wealth-holdings")||"[]"))}catch{}},[]);
 const codes=useMemo(()=>Array.from(new Set([...INDEX_CODES,...watch,...holdings.map(h=>h.code),selected])),[watch,holdings,selected]);
 const refresh=async()=>{setLoading(true);setError("");try{const r=await fetch(`/api/market?codes=${codes.join(",")}`,{cache:"no-store"}),j=await r.json();if(!j.ok)throw new Error(j.error);setQuotes(j.quotes);setStamp(new Date(j.fetchedAt).toLocaleString("zh-CN"))}catch(e){setError(e instanceof Error?e.message:"行情请求失败")}finally{setLoading(false)}};
 useEffect(()=>{refresh();const t=setInterval(refresh,30000);return()=>clearInterval(t)},[codes.join(",")]);
 useEffect(()=>{fetch(`/api/market?type=kline&code=${selected}`).then(r=>r.json()).then(j=>setBars(j.bars||[])).catch(()=>setBars([]))},[selected]);
 const map=useMemo(()=>{const m:Record<string,Quote>={};quotes.forEach(q=>{m[`${q.market}.${q.code}`]=q;if(!INDEX_CODES.includes(`${q.market}.${q.code}`))m[q.code]=q});return m},[quotes]); const q=map[selected];
 const closes=bars.map(b=>b.close),ma=(n:number)=>closes.length>=n?closes.slice(-n).reduce((a,b)=>a+b,0)/n:NaN;
 const signal=!q?"数据不足":q.price>ma(20)&&ma(20)>ma(60)?"趋势偏强，等待回踩确认":q.price<ma(20)&&ma(20)<ma(60)?"趋势偏弱，优先控制风险":"区间震荡，避免追涨杀跌";
 const holdingValue=holdings.reduce((s,h)=>s+(map[h.code]?.price||0)*h.shares,0),holdingCost=holdings.reduce((s,h)=>s+h.cost*h.shares,0);
 const saveWatch=(w:string[])=>{setWatch(w);localStorage.setItem("wealth-watch",JSON.stringify(w))}; const saveHold=(h:typeof holdings)=>{setHoldings(h);localStorage.setItem("wealth-holdings",JSON.stringify(h))};
 const addCode=()=>{const c=newCode.replace(/\D/g,"").slice(0,6);if(c.length===6&&!watch.includes(c))saveWatch([...watch,c]);setNewCode("")};
 const path=bars.slice(-60).map((b,i,a)=>{const vals=a.map(x=>x.close),mn=Math.min(...vals),mx=Math.max(...vals);return `${(i/(a.length-1||1))*100},${85-((b.close-mn)/(mx-mn||1))*70}`}).join(" ");
 const filtered=chapters.map((x,i)=>({x,i})).filter(({x})=>x.join("").includes(learnQ)); const total=principal*Math.pow(1+rate/100,years);
 return <main><header><div className="brand"><span>↗</span><b>WEALTH OS</b><small>真实数据投资工作台</small></div><nav>{[["market","市场"],["watch","自选"],["portfolio","持仓"],["strategy","策略"],["learn","学习"]].map(x=><button key={x[0]} className={tab===x[0]?"active":""} onClick={()=>setTab(x[0])}>{x[1]}</button>)}</nav><div className="head-actions"><span className="status">{error?`数据异常：${error}`:`真实行情 · ${stamp||"连接中"}`}</span><button onClick={refresh}>{loading?"同步中":"↻ 刷新"}</button></div></header>
 <section className="page realapp">{tab!=="learn"&&<div className="sourcebar"><b>数据口径</b> 东方财富 push2 / push2his · 行情约30秒刷新 · K线前复权 · <span>最后成功 {stamp||"-"}</span></div>}
 {tab==="market"&&<><div className="section-title"><span><small>REAL MARKET</small><h2>市场总览</h2></span></div><div className="index-grid">{INDEX_CODES.map(c=>{const x=map[c];return <article className="index-card" key={c}><div><span>{x?.name||c}</span><b className={(x?.changePct||0)>=0?"up":"down"}>{x?pct(x.changePct):"-"}</b></div><strong>{x?.price??"-"}</strong><p>高 {x?.high??"-"}　低 {x?.low??"-"}</p><p>成交额 {x?money(x.amount):"-"}</p></article>})}</div><div className="lower-grid"><article className="panel market-focus"><div className="section-head"><div><small>{q?.name||selected} · {selected}</small><h2>{q?.price??"-"} <em className={(q?.changePct||0)>=0?"up":"down"}>{q?pct(q.changePct):"-"}</em></h2></div><select value={selected} onChange={e=>setSelected(e.target.value)}>{watch.map(c=><option key={c} value={c}>{map[c]?.name||c}</option>)}</select></div><svg viewBox="0 0 100 90" preserveAspectRatio="none"><polyline points={path} fill="none" stroke="#049b93" strokeWidth="1.2"/></svg><div className="quote-detail"><span>开盘 <b>{q?.open??"-"}</b></span><span>最高 <b>{q?.high??"-"}</b></span><span>最低 <b>{q?.low??"-"}</b></span><span>换手 <b>{q?.turnover??"-"}%</b></span><span>PE <b>{q?.pe??"-"}</b></span><span>PB <b>{q?.pb??"-"}</b></span></div></article><article className="panel decision-live"><small>系统观察</small><h2>{signal}</h2><p>MA20 {Number.isFinite(ma(20))?ma(20).toFixed(2):"-"} · MA60 {Number.isFinite(ma(60))?ma(60).toFixed(2):"-"}</p><p>基于180个交易日前复权日线计算；只描述当前结构，不预测收益。</p></article></div></>}
 {tab==="watch"&&<><div className="toolrow"><div><h1>自选股</h1><p>代码保存在当前设备，行情来自真实接口。</p></div><div><input value={newCode} onChange={e=>setNewCode(e.target.value)} placeholder="输入6位股票代码"/><button onClick={addCode}>添加</button></div></div><div className="stock-table"><div className="tr th"><span>名称 / 代码</span><span>最新</span><span>涨跌幅</span><span>成交额</span><span>PE / PB</span><span>操作</span></div>{watch.map(c=>{const x=map[c];return <div className="tr" key={c} onClick={()=>{setSelected(c);setTab("market")}}><span><b>{x?.name||"加载中"}</b><small>{c}</small></span><span>{x?.price??"-"}</span><span className={(x?.changePct||0)>=0?"up":"down"}>{x?pct(x.changePct):"-"}</span><span>{x?money(x.amount):"-"}</span><span>{x?.pe??"-"} / {x?.pb??"-"}</span><button onClick={e=>{e.stopPropagation();saveWatch(watch.filter(i=>i!==c))}}>移除</button></div>})}</div></>}
 {tab==="portfolio"&&<><div className="toolrow"><div><h1>我的持仓</h1><p>仅保存在当前浏览器，不上传个人资产数据。</p></div><button onClick={()=>saveHold([...holdings,{code:"600519",shares:100,cost:1400}])}>＋ 添加一笔</button></div><div className="portfolio-summary"><div><small>持仓市值</small><b>¥ {money(holdingValue)}</b></div><div><small>持仓成本</small><b>¥ {money(holdingCost)}</b></div><div><small>浮动盈亏</small><b className={holdingValue-holdingCost>=0?"up":"down"}>¥ {money(holdingValue-holdingCost)}</b></div></div>{holdings.length===0?<div className="empty">暂无持仓，点击“添加一笔”开始记录。</div>:<div className="stock-table">{holdings.map((h,i)=>{const x=map[h.code];return <div className="tr holding" key={i}><input value={h.code} onChange={e=>{const z=[...holdings];z[i]={...h,code:e.target.value.replace(/\D/g,"").slice(0,6)};saveHold(z)}}/><input type="number" value={h.shares} onChange={e=>{const z=[...holdings];z[i]={...h,shares:+e.target.value};saveHold(z)}}/><input type="number" value={h.cost} onChange={e=>{const z=[...holdings];z[i]={...h,cost:+e.target.value};saveHold(z)}}/><span>{x?.name||"同步中"} · 市值 ¥{money((x?.price||0)*h.shares)}</span><button onClick={()=>saveHold(holdings.filter((_,j)=>i!==j))}>删除</button></div>})}</div>}</>}
 {tab==="strategy"&&<><div className="strategy-title"><div><span className="eyebrow">RULE-BASED ENGINE</span><h1>纪律策略室</h1><p>所有指标都由真实前复权日线计算，不使用固定演示结论。</p></div><select value={selected} onChange={e=>setSelected(e.target.value)}>{watch.map(c=><option key={c} value={c}>{map[c]?.name||c}</option>)}</select></div><article className="decision panel"><small>当前结构判断</small><h2>{signal}</h2><p>{q?.name}（{selected}）最新价 {q?.price??"-"}；20日均线 {Number.isFinite(ma(20))?ma(20).toFixed(2):"-"}，60日均线 {Number.isFinite(ma(60))?ma(60).toFixed(2):"-"}。均线只用于描述趋势，不单独构成交易信号。</p><div className="decision-metrics"><div><b>{q?pct(q.changePct):"-"}</b><span>当日涨跌</span></div><div><b>{q?.pe??"-"}</b><span>PE(TTM)</span></div><div><b>{q?.pb??"-"}</b><span>市净率</span></div><div><b>{bars.length}</b><span>有效日线样本</span></div></div></article></>}
 {tab==="learn"&&<><div className="learn-hero"><div><span className="eyebrow">WEALTH ACADEMY</span><h1>金融知识，从基础到高阶</h1><p>每个知识点包含理论、公式、数字案例和风险边界。</p></div><div className="progress-card"><div className="ring"><b>{Math.round(((lesson+1)/chapters.length)*100)}%</b></div><div><small>当前章节</small><h3>{chapters[lesson][1]}</h3><p>{lesson+1} / {chapters.length}</p></div></div></div><div className="academy"><aside><input value={learnQ} onChange={e=>setLearnQ(e.target.value)} placeholder="搜索术语或知识点"/>{filtered.map(({x,i})=><button className={lesson===i?"active":""} key={i} onClick={()=>setLesson(i)}><small>{x[0]} · {String(i+1).padStart(2,"0")}</small><b>{x[1]}</b></button>)}</aside><article className="lesson panel"><span className="eyebrow">{chapters[lesson][0]}篇 · 知识点 {lesson+1}</span><h1>{chapters[lesson][1]}</h1><p className="lead">{chapters[lesson][2]}</p><div className="tip"><b>学习原则：</b>先理解适用条件，再使用公式；历史数据与计算结果都不等于未来收益。</div><hr/><h3>复利互动案例</h3><label>本金 <input type="number" value={principal} onChange={e=>setPrincipal(+e.target.value)}/></label><label>年化假设 {rate}% <input type="range" min="0" max="20" value={rate} onChange={e=>setRate(+e.target.value)}/></label><label>年限 {years}年 <input type="range" min="1" max="40" value={years} onChange={e=>setYears(+e.target.value)}/></label><div className="result"><small>教学演算终值</small><strong>¥ {Math.round(total).toLocaleString("zh-CN")}</strong><span>不含税费，不代表收益承诺</span></div></article></div></>}
 </section><footer><span>WEALTH OS · 真实数据、明确口径、失败不造数</span><span>研究与学习辅助，不构成投资建议</span></footer></main>
}
